name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
      - feature/*
      - writer

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy dev
        if: github.ref != 'refs/heads/master'
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          CUSTOM_DOMAIN: canvas.devx.pw
          # EXTRA_PACKAGES: build-base

      - name: Deploy Prod
        if: github.ref == 'refs/heads/master'
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          CUSTOM_DOMAIN: devx.pw
          # EXTRA_PACKAGES: build-base
